### ISSUE TITLE
Clarifications with resourceful-mongo use and settings

### ISSUE THREAD

**Issue by ericchaves** [codebrew/resourceful-mongo#4]
Hi guys,

I'm not sure if this is the best place to ask for questions since it was supposed to manage issues, but I'm not aware of other place to ask.

I'm kinda lost with the proper use of resourceful-mongo use. The example at the readme is now a working code (running it as is produces a TypeError: Cannot call method 'collection' of undefined) and when digging into the code and tests I got confused because define mongo URI and collection, collections and other stuff  in several different places. Those are declared when defining a resource and later on by calling resourceful.use, but they have conflicting parameters (for example, they point to different databases).

Also by the readme sample I should define "resourceful" by requiring resourceful-mongo, but in the tests both resourceful and resourceful-mongo are being defined.

Could you guys point me a working sample application or help me out with the proper way to use resourceful-mongo?

Finally, I know resourceful-mongo i not yet production ready, but is it aiming this stage in short time?  Right now I'm starting a new project based on Resourceful and I'm not sure if I should make use of the mongo-native driver or if I follow along with resourceful-mongo.

Would love to hear your thoughts on this matter.

Thanks in advance,

Eric

**Comment by Raynos** [comment]
When I found resourceful-mongo it wasn't worked on for a period of time.

I applied a few bug fixes and then quickly came to the conclusion that resourceful does not work cleanly with mongodb at all.

Since then I wrote [mongo-col](https://github.com/raynos/mongo-col)

I have no intend to maintain resourceful-mongo.

**Comment by ericchaves** [comment]
hi Rynos,

Thanks for the update. I'll take a look at mongo-col then.

Best regards,

Eric
